In [25]:
import pandas as pd
import numpy as np
from statsmodels.stats.proportion import proportions_ztest

In [3]:
df1 = pd.read_csv("open_ended_data_coded.csv").fillna(0)
df1

,participant_code,open_badge,Open-minded,Popular,Activity,Civil,Uncivil,Extreme/Controversial,Moderate,DK,No Answer,Non Sequitur,Hard to Code,Other,feedback,Glitch,Other.1
0,8gch37,I think the badge would be earned by having co...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,"When scrolling, the feed would sometimes glitc...",1.0,0
1,zf1er9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,I didn't experience any harassment or glitches.,0.0,0
2,nyuhem,Respectfull comments about their own opinion,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,"No, it was actually nice",0.0,0
3,2d3axv,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,No,0.0,0
4,3y76hr,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,No,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,6fxpk1,"Getting lots of interaction, being popular",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Nope,0.0,0
1531,ahr9ft,Be engaged like posts and comments,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,No,0.0,0
1532,pwghnt,Engaging frequently and politely,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Nope,0.0,0
1533,nbwdbg,"High social engagement, likes and interaction ...",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,"No, thank you!",0.0,0
1534,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0

In [8]:
df2 = pd.read_csv("Cleaned_study_data.csv")[['participant_code','treatment']]
df2

     participant_code  treatment
0              8gch37          1
1              nyuhem          0
2              gw6r7f          0
3              17xpyv          1
4              hfyv7m          0
...               ...        ...
1038           r9hyrv          1
1039           3naupc          0
1040           6fxpk1          0
1041           pwghnt          0
1042           nbwdbg          0

[1043 rows x 2 columns]

In [10]:
df = df1.merge(df2, on="participant_code", how="right")
df

,participant_code,open_badge,Open-minded,Popular,Activity,Civil,Uncivil,Extreme/Controversial,Moderate,DK,No Answer,Non Sequitur,Hard to Code,Other,feedback,Glitch,Other.1,treatment
0,8gch37,I think the badge would be earned by having co...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,"When scrolling, the feed would sometimes glitc...",1.0,0,1
1,nyuhem,Respectfull comments about their own opinion,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,"No, it was actually nice",0.0,0,0
2,gw6r7f,Sharing thoughts that are generally shared by ...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,No problems,0.0,0,0
3,17xpyv,I think it was called the open minded badge an...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Nope I have no glitches to report or any bad b...,0.0,0,1
4,hfyv7m,Making opinions that others agree with will he...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,r9hyrv,I like the open minded one. I'm afraid a badge...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,No. I assume it's early development but the re...,1.0,Commenting issues,1
1039,3naupc,I think it comes from engaging content that ga...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,No harassment or glitches. All went well.,0.0,0,0
1040,6fxpk1,"Getting lots of interaction, being popular",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Nope,0.0,0,0
1041,pwghnt,Engaging frequently and politely,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,Nope,0.0,0,0
1042,nbwdbg,"High social engagement, likes and interaction ...",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,"No, thank you!",0.0,0,0

In [11]:
treat = df[df.treatment == 1]
control = df[df.treatment == 0]

In [12]:
list(df.columns)

['participant_code',
 'open_badge',
 'Open-minded',
 'Popular',
 'Activity',
 'Civil',
 'Uncivil',
 'Extreme/Controversial',
 'Moderate',
 'DK',
 'No Answer',
 'Non Sequitur',
 'Hard to Code',
 'Other',
 'feedback',
 'Glitch',
 'Other.1',
 'treatment']

In [16]:
df['open_badge'].size

1043

In [29]:
set(df.Other)

{"'Good'",
 "'Good' quality",
 "'Good' quality, Articulate",
 0,
 'Agreeable',
 'Anti-immigration',
 'Articulate',
 'Detailed',
 'Factual',
 'Helpful',
 'Honest',
 'Humor',
 'Informative',
 'Informative, Agreeable',
 'Informative, Insightful, Interesting',
 'Informative, Interesting',
 'Informative, Thoughtful',
 'Insightful',
 'Intellectually humble',
 'Interesting',
 'Knowledgeable',
 'Knowledgeable, Humor',
 'Liberal',
 'Low effort',
 'Meaningful',
 'Passionate',
 'Politically correct',
 'Populist',
 'Positive tone',
 'Positive tone, Helpful, Insightful',
 'Pro-gun control',
 'Rational',
 'Relevant',
 'Relevant, Interesting',
 'Strong opinion',
 'Strong opinion, Articulate',
 'Strong opinion, Factual, Rational',
 'Suspected bots',
 'Thoughtful',
 'Thoughtful, Passionate',
 'Thoughtful, Rational',
 'Truthful, Factual',
 'Truthful, Relevant'}

In [36]:
D = []

for x in ['Open-minded','Popular','Activity','Civil','Uncivil','Extreme/Controversial',
          'Moderate','DK','No Answer','Non Sequitur','Hard to Code']:
    datum = {"code": x}
    t = treat[x]
    c = control[x]
    z = proportions_ztest([t.sum(), c.sum()],[t.size, c.size])
    D.append({"code": x,
              "control": c.mean(),
              "treat": t.mean(),
              "p": z[1],
              "z": z[0],
              "ratio": t.mean()/c.mean()})

pd.DataFrame(D).sort_values("ratio", ascending=False)

,code,control,treat,p,z,ratio
0,Open-minded,0.018109,0.593407,3.696358e-88,19.904817,32.769231
3,Civil,0.082495,0.415751,8.834007e-35,12.302017,5.039712
6,Moderate,0.008048,0.014652,3.178836e-01,0.998816,1.820513
7,DK,0.004024,0.007326,4.812935e-01,0.704224,1.820513
9,Non Sequitur,0.008048,0.009158,8.466122e-01,0.193443,1.137821
8,No Answer,0.072435,0.069597,8.585102e-01,-0.178271,0.960826
4,Uncivil,0.002012,0.001832,9.469186e-01,-0.066577,0.910256
10,Hard to Code,0.070423,0.060440,5.142343e-01,-0.652259,0.858242
2,Activity,0.255533,0.108059,5.157851e-10,-6.214225,0.422875
1,Popular,0.613682,0.056777,2.380937e-82,-19.222898,0.092518
5,Extreme/Controversial,0.046278,0.003663,6.990184e-06,-4.493987,0.079153