In [1]:
import os
import pandas as pd
import numpy as np
from collections import defaultdict, Counter
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sb
import csv
from scipy import stats
from scipy.spatial.distance import cosine
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [2]:
post_info = pd.read_csv("perspective_toxicity.csv")

post_info['ih_austin_a'] = np.mean([post_info.CURIOSITY_EXPERIMENTAL,
                                    post_info.NUANCE_EXPERIMENTAL,
                                    post_info.RESPECT_EXPERIMENTAL], axis=0)

post_info['ih_austin_b'] = np.mean([post_info.CURIOSITY_EXPERIMENTAL,
                                    post_info.NUANCE_EXPERIMENTAL,
                                    post_info.REASONING_EXPERIMENTAL,
                                    post_info.RESPECT_EXPERIMENTAL], axis=0)

post_info['tox_austin_a'] = post_info.TOXICITY_EXPERIMENTAL

post_info['tox_austin_b'] = np.mean([post_info.TOXICITY_EXPERIMENTAL,
                                     post_info.IDENTITY_ATTACK_EXPERIMENTAL,
                                     post_info.INSULT_EXPERIMENTAL,
                                     post_info.THREAT_EXPERIMENTAL,
                                     post_info.SEXUALLY_EXPLICIT], axis=0)

In [3]:
for x in ['CURIOSITY_EXPERIMENTAL','NUANCE_EXPERIMENTAL','REASONING_EXPERIMENTAL','RESPECT_EXPERIMENTAL',
          'ih_austin_a','ih_austin_b']:
    posts = post_info.sort_values(x, ascending=False).head(10)
    print(x)
    for ind, row in posts.iterrows():
        print(">> " + row['postOrCommentText'])
    print()

CURIOSITY_EXPERIMENTAL
>> What is your objective criteria for identifying those people though? I agree wholeheartedly, but how can you stop someone for lying or hiding their issues without tighter background checks?
>> Agree completely. What is your take on the mass migrations into the country through our Southern border?
>> Hmmm how do we think outbursts and crimes of passion play into this from people who wouldn’t typically be considered violent? You can’t police everyone but wouldn’t stricter gun laws help limit deaths due to gun violence over all?
>> Could you further elaborate on why you feel there should be gun bans?
>> What exactly is reasonable gun legislation? What would that look like? What exactly would it entail?
>> I agree, but wouldn't redtricts like background checks and no sales to domestic violence convicted persons be ok?
>> What would those special circumstances look like though? Who is allowed to have access to these guns and who is not?
>> I'd be interested in your expanding upon what you mean by American identity and culture. Do you mean indigenous peoples culture or something else?
>> Where is the proof of this? How do you know that immigrants fill these jobs?
>> Could I ask what exactly your argument is on the matter?

NUANCE_EXPERIMENTAL
>> I also don’t understand the claims that undocumented workers are unfairly accessing public assistance programs. I used to work for a federally orchestrated program and for programs like SNAP/Food Stamps, you had to prove your eligibility by citizenship or naturalization. So, kids might be eligible if they’re citizens born here, but their parents aren’t included in the family allotment. To be clear: kids need adults to negotiate their benefits for them, even if those adults aren’t documented.
>> Both sides have good and valid points. To start, I do believe this country would not be what it is today without immigration. At the same time, there are pockets throughout the SW border that do in fact see elevated crime due to illegal immigration. To be clear, it's not widespread as many politicians will have you believe. So, I feel it's okay to address pockets and build barriers if need be.

On the other end, we need to make legal ways of entering the country easier and we need to be welcoming.
>> Unlike most people think, the truth is right in the middle. Most of the immigrants come to the US for better life and devote their time and efforts to this purpose. Regardless of line of work they complete, they still can and most of them do pay taxes via ITIN (individual tax ID), pay for medical services without insurance and spend and consume just like regular Americans. They do not come to take away from you, they come to bring to the table and contribute.
However, some immigrants do come from a shady background and try to flee to the US since they’re being prosecuted back home. Still, it is CBP’s job to catch these people and return them home. I also think that the federal government need to come up with a transition status for all undocumented immigrants that will not be equal to residents however will grant them certain rights and oblige them with certain duties.
>> I believe allowing illegal immigration is immoral because of the cartel trafficking of little girls, blackmail, and drug distribution. We should make legal immigration humane and not so troublesome. On the other hand we should never shut our borders to someone who is not a convicted criminal, no matter what they may look like or how different they are. Violent offenders in general should be someone we don’t consider. Nonviolent misdemeanors shouldn’t be something that stops a person from coming automatically and should be a case by case bases using rational logic. Taking variables into consideration such as the age of the person when they committed the crime because we all make mistakes.
 We need to love others without compromising the safety of our loved ones and it’s a tough line to balance on.
>> I'm not any kind of pro on gun control and sometimes I may not articulate myself well, but I fully believe there needs to be stronger gun control, and some sort of checks put in place on gun owners for the whereabouts of their guns. I have a personal example: my dad is abusive towards my mom and always has been. My sister called the cops only once that went on his records, years ago. He tried to buy a gun in the last year from Walmart and he was denied because of that record. That didn't stop him though. My aunt had a gun and gave it to him, so he now has a gun in the house anyway. There needs to be checks on these kinds of things so this doesn't happen.
>> Gun control is such a controversial matter. In all actuality, if we ban guys, we are gonna have riots. Which I see both sides. There are people who need guns due to living in the country because there are coyotes who try jotting the cattle or their pets. There’s also when you need to protect your self due to the fact someone attacked you. But I also see the side where people think we should ban them. Why? Because regardless of what laws we put in place in order of who can buy guns and who can not, criminals will illegally obtain them. That’s just how it is in life. It won’t stop anything. I’m not sure what the exact answer is and there’s not really a middle of the road compromise that can be made. I think we need to try both ways because the homicide rates need to go down.
>> I’ve come up with a compromise. I will support lax gun laws IF and only if we start a program where anyone who is homeless is given a voucher for a free firearm. As many people have said, guns are necessary for protection. And homeless people are the most vulnerable among us. What better way to support the second amendment than by empowering folks who need it the most? I have a feeling that this legislation would create a ripple effect or a trickle-down effect that will lead to positive change in other areas as well. For example, I think it would fix the housing crisis. For example, suppose you don’t like the thought of a homeless person having a gun. Not a problem! Just help him get housing. Problem solved!
>> I know that Americans are very proud of being unique and feel that The Constitution makes us special. But I think it is important that we look at the reality of how banning guns in other countries has worked. Perhaps we don't have to go as far as a complete ban as they have in Australia and the UK, but maybe it wouldn't be impossible to enforce less strict laws. Laws such as domestic abuse means no guns for the abuser. This really seems like basic common sense. Especially when you look at mass shootings and see that very nearly 100% of the time there is a domestic abuse background.
>> This may be true, but what we need to think about here is the difference between correlation and causation. The places where most gun violence occurs tend to be large urban areas where politics lean left and consequently which have more restrictive gun laws. However, this does NOT mean that restrictive gun laws are the cause of the mayhem. It is likely due to the fact that cities have more activity in general, and therefore, higher rates of illegal activity as well.
>> I think that we do have a gun problem in this country. While I'm not for the government stripping away guns people already have or someone's valid reason to have a gun (.ie purely self defense in an extremely dangerous situation) I do think stricter gun laws and control can be passed. I do think people that purchase guns should have to go through a strict background and mental health check to make sure they aren't winding up with people that end up on terrible shooting sprees. I also think mental health checkups for gun owners should not be a one time only occurrence, but happen yearly or so, much like your annual doctor visit.

REASONING_EXPERIMENTAL
>> I’ve come up with a compromise. I will support lax gun laws IF and only if we start a program where anyone who is homeless is given a voucher for a free firearm. As many people have said, guns are necessary for protection. And homeless people are the most vulnerable among us. What better way to support the second amendment than by empowering folks who need it the most? I have a feeling that this legislation would create a ripple effect or a trickle-down effect that will lead to positive change in other areas as well. For example, I think it would fix the housing crisis. For example, suppose you don’t like the thought of a homeless person having a gun. Not a problem! Just help him get housing. Problem solved!
>> Both sides have good and valid points. To start, I do believe this country would not be what it is today without immigration. At the same time, there are pockets throughout the SW border that do in fact see elevated crime due to illegal immigration. To be clear, it's not widespread as many politicians will have you believe. So, I feel it's okay to address pockets and build barriers if need be.

On the other end, we need to make legal ways of entering the country easier and we need to be welcoming.
>> I know that Americans are very proud of being unique and feel that The Constitution makes us special. But I think it is important that we look at the reality of how banning guns in other countries has worked. Perhaps we don't have to go as far as a complete ban as they have in Australia and the UK, but maybe it wouldn't be impossible to enforce less strict laws. Laws such as domestic abuse means no guns for the abuser. This really seems like basic common sense. Especially when you look at mass shootings and see that very nearly 100% of the time there is a domestic abuse background.
>> Immigration is a most complex issue and there are no easy answers. On the positive side, there is economic growth, culture, diversity and bringing more people together. On the negative side, there is a language barrier, competition and security issues. We should all, no matter what opinion, have beneficial conversations on how to meet the challenges and opportunities that immigration presents and how to manage these solutions most effectively and efficiently.
>> While the current system is clearly not working as intended, we greatly rely on folks from other countries to help in many key industries. We need to figure out a path to citizenship for many who are already here as well as correct the current problems on the border. Crossing illegally is both highly dangerous as well as unhelpful for the country as a whole.
>> I believe guns can be handled safely but society needs to make sure that people who are getting access to guns are qualified to handle them appropriately. I think it is important to educate and enforce restrictions so that only people who can be trusted with guns are allowed access to them. I think more rigorous training and education should be given to those interested in purchasing guns. Perhaps the price of guns needs to be raised significantly as well so only those who are truly serious about acquiring firearms are willing to purchase them.
>> Safety is paramount, I agree. My hesitation at a wall is that while it is a barrier, it is not THE barrier. The images we have been shown are haunting and my hope is we can find a way to ease the tensions and trauma felt from those attempting asylum and those living and working in border towns, etc.
>> I agree that with proper safety training, guns are a lot safer. The first thing I learned during hunting safety class was to always, #1 rule, is to make sure your gun is pointed in a safe direction before doing anything. I believe there should be a mandatory gun safety class before you are able to purchase a firearm.
>> I believe in gun reform vs gun control. I do believe that as Americans we have the right to bear arms, but I also believe that there should be some reform to just being able to go in and buy a gun and walk out same day. I believe a waiting period should be in place, I think that a system should be developed where you have to take a FREE class to learn about gun safety, maintenance and training. A class that is volunteer based where an instructor themselves has to go through the class.
>> We are an immigrant country. It has given us our strength and identity. It’s how we started. That said, I believe we do have to have some control over the numbers entering; there cannot be an open border policy. The idea of a physical wall is more symbolic than effective. I think we can have good immigration policy and welcome qualified people into the country at the same time.

RESPECT_EXPERIMENTAL
>> Absolutely.  I try to advocate daily.  Thanks so much for your comment..
>> I agree! They add great culture and ideas to our society! I appreciate the interactions
>> 100% agree with that. Thanks for the chat!
>> Exactly! I love your perspective on this topic so much!!
>> Agree completely!! Immigration is so important for these reasons
>> I agree completely, and that’s a wonderful point you made.
>> Huge agree and appreciate you considering balance as well. It's a complex situation and not everything needs to be extreme. Most good solutions require balance!
>> Good points about the registration and gun locks! Definitely agree with you 👍🏼
>> Great analysis. Totally agreed.
>> I agree 100%! Thank you for this!!

ih_austin_a
>> This it totally true. People who really want a gun will find a way to get one. However, I wonder how many people who shouldn’t own guns and try to would still not be able to get one? Barriers for anything don’t always work, so maybe the focus should be on how much change it would bring, not focusing on if it would be 100% effective enough (which in my opinion, is impossible to achieve).
>> I definitely agree that there are people who live where having guns are used more like tools for safety,  getting food, or protecting the way you make a living.  I believe that is a right we have.  I guess I think we could help keep others safe more by having a way to obtain guns that proves we will be responsible gun owners
>> Safety is paramount, I agree. My hesitation at a wall is that while it is a barrier, it is not THE barrier. The images we have been shown are haunting and my hope is we can find a way to ease the tensions and trauma felt from those attempting asylum and those living and working in border towns, etc.
>> Completely agree with you! My only source of stress is the difficulties we may face with screening people. How do we know if someone is actually a good person and how do we know we aren't making a mistake?
>> I absolutely agree. Working in the construction field, many contractors are immigrants.  They are focused, skilled, and they don’t try to gauge you with high prices.
>> I agree. Immigrants are people who are simply seeking a better life. What’s wrong with seeking the American Dream? They’re people, too, and deserve to be treated as such.
>> Stricter laws would help make it harder for the wrong people to obtain the guns and it is a step in the right direction in my opinion but what can be done to better deter guns getting into the wrong hands? I am at a loss regarding this personally, but I do agree and support stricter regulations being put into place.
>> I agree in someways immigration is dangerous. We don’t know who immigrating. This is why it’s so important that it’s done correctly and legally, so we can look at who’s coming into this country.
>> Right, I agree with that but it's not exactly doing anything new they already do background checks for people buying guns. but yeah they do what they can, I think the whole issue politically is what should or shouldn't they do moving forward.
>> Agreed, foreign work visas provide much needed support to help grow the america economy. If a more accessible visa is provided to those willing to work low end jobs and allows them to work legally and pay taxes, i think such a program could boost the economy greatly

ih_austin_b
>> I definitely agree that there are people who live where having guns are used more like tools for safety,  getting food, or protecting the way you make a living.  I believe that is a right we have.  I guess I think we could help keep others safe more by having a way to obtain guns that proves we will be responsible gun owners
>> Safety is paramount, I agree. My hesitation at a wall is that while it is a barrier, it is not THE barrier. The images we have been shown are haunting and my hope is we can find a way to ease the tensions and trauma felt from those attempting asylum and those living and working in border towns, etc.
>> This it totally true. People who really want a gun will find a way to get one. However, I wonder how many people who shouldn’t own guns and try to would still not be able to get one? Barriers for anything don’t always work, so maybe the focus should be on how much change it would bring, not focusing on if it would be 100% effective enough (which in my opinion, is impossible to achieve).
>> Agreed, foreign work visas provide much needed support to help grow the america economy. If a more accessible visa is provided to those willing to work low end jobs and allows them to work legally and pay taxes, i think such a program could boost the economy greatly
>> I agree that with proper safety training, guns are a lot safer. The first thing I learned during hunting safety class was to always, #1 rule, is to make sure your gun is pointed in a safe direction before doing anything. I believe there should be a mandatory gun safety class before you are able to purchase a firearm.
>> I agree. A relative of mine was inappropriately 5150'd after a false report was made against him and as a result is unable to own a firearm for at least 5 years. He had a large collection of firearms, mostly family heirlooms and old war memorabilia, that was all confiscated and auctioned by the city police. I tried to buy them back to hold for him until the waiting period was over, but they were too expensive. He was devastated. It makes me wonder who gets to determine who the real threats are meanwhile those who obtain firearms illegally will continue to do so.
>> Exactly.  The various cultures helped USA broaden knowledge of each cultures and even students from many universities go to their countries to help and it is definitely enrichment experience for them and for us to learn to open our eyes.  One should help one another regardless.
>> I absolutely agree. Working in the construction field, many contractors are immigrants.  They are focused, skilled, and they don’t try to gauge you with high prices.
>> Completely agree with you! My only source of stress is the difficulties we may face with screening people. How do we know if someone is actually a good person and how do we know we aren't making a mistake?
>> While I understand the pro gun control perspective, and agree with certain points I’d like to add some key points to consider on the anti gun control side:
1 self defense
2 oppression
3 constitutional right.

For me self defense is the biggest reason citizens need to have this right. Criminals and intruders have guns and how else would a person protect themselves aside from calling the police. The effectiveness of firearms in self defense cannot compare to calling the cops and hoping they arrive in time.

In [4]:
for x in ["TOXICITY_EXPERIMENTAL", "IDENTITY_ATTACK_EXPERIMENTAL", "INSULT_EXPERIMENTAL",
          "THREAT_EXPERIMENTAL", "SEXUALLY_EXPLICIT", "tox_austin_b"]:
    posts = post_info.sort_values(x, ascending=False).head(10)
    print(x)
    for ind, row in posts.iterrows():
        print(">> " + row['postOrCommentText'])
    print()

TOXICITY_EXPERIMENTAL
>> i think u should suck a dick
>> Clueless fucking liberals don't get it
>> Way to paint brush and fucking label people
>> A border wall is the stupidest idea from a traitor scamming orange person with fake hair named Donold
>> You are a fool if you think it will stop it.  Look at drugs, hows that fight going?
>> Dumb  sooooo dumb
>> . Any idiot can use a military style weapon to spray bullets uncontrolled and do serious damage. While a regular gun can still cause harm, I’d argue it would require more skill to devastate a mass population. There would also be a greater chance of stopping a lone gunmen.
>> I think the government needs to pull their heads out of their backside orifices and get a better grip on the southern border…. Obvious what they are doing now isn’t working.  And no fn wall…. Thats a waste of money and looks stupid af.
>> American citizens are dumb for thinking their guns would be enough to stop an authoritarian government
>> Guns don't kill people. I kill people.

IDENTITY_ATTACK_EXPERIMENTAL
>> I think immigrants are overall bad for our country. They take out jobs, food,   and land. They bring drugs, violence and sickness. There are other ways to help them besides bringing them into our country. Let's help them make there own countries better as we can without hurting our own country in the process.
>> Immigrants cause more harm than good in this country, they should be stopped
>> I beg to differ. We should have restrictions on drunks and wife beaters and white radical people
>> The US is a melting pot of immigrants but as soon as they are brown there's a problem.
>> Exactly. Everyone here is descended from a immigrant. It seems to me though, that the only immigrants these people have a problem with are the colored ones
>> American citizens are dumb for thinking their guns would be enough to stop an authoritarian government
>> Yes! Build the wall longer and higher! Stop the immigrants
>> Some illegals are not good. Many funnel drugs and commit crimes
>> Who are you defending yourself from that you can murder by accident instead of using something less lethal? Texas laws allowing those to murder with guns if they're ""trespassing""  are biased against brown and Black people.
>> NRA members don’t need to commit mass murder because they’re rich and prospering and have access to any resource they could want. Most mass shooters are poor, mentally ill, and have been radicalized online by white supremacists.

INSULT_EXPERIMENTAL
>> A border wall is the stupidest idea from a traitor scamming orange person with fake hair named Donold
>> You are a fool if you think it will stop it.  Look at drugs, hows that fight going?
>> Clueless fucking liberals don't get it
>> . Any idiot can use a military style weapon to spray bullets uncontrolled and do serious damage. While a regular gun can still cause harm, I’d argue it would require more skill to devastate a mass population. There would also be a greater chance of stopping a lone gunmen.
>> Dumb  sooooo dumb
>> Some people are sick and or dumb. Thus being said it only takes 1 to ruin it for the majority of us
>> I think the government needs to pull their heads out of their backside orifices and get a better grip on the southern border…. Obvious what they are doing now isn’t working.  And no fn wall…. Thats a waste of money and looks stupid af.
>> Is it just me or are the men and women in the Republican party really this ignorant.
>> American citizens are dumb for thinking their guns would be enough to stop an authoritarian government
>> Seems like we need some mental health assessments with gun ownership. I can deal with grown people killing each other but when kids kill kids, there is a problem.  In a nearby town a year or two ago, the gun was purchased for the kid by his parents --who knew he was having issues.  You can't fix stupid but you should restrict its gun ownership.

THREAT_EXPERIMENTAL
>> Guns don't kill people. I kill people.
>> You can't get a second amendment guy to explain his devotion to 2a in a way that doesn't translate to ""I know I don't make sense. I just really wanna get guns and shoot them.""
>> Given a second chance ? They could use the gun again and maybe kill someone
>> we need guns so we can shoot back
>> I am not just pro death penalty, I think we should add a torture penalty on top of it. The real scum of the world should be tortured as they await their eventual death.
>> Have you ever had a gun pointed at your head?
>> If there were no guns then a good guy with a knife will stab a bad guy with a knife
>> Suicide Jamie.
>> That will simply pen them in to die out of sight
>> GUNS DON'T KILL PEOPLE... PEOPLE KILL PEOPLE

SEXUALLY_EXPLICIT
>> i think u should suck a dick
>> I have a crush on a man named Quentin he is really sweet and hot
>> We need to stop encouraging illegal immigration; it causes migrants to take dangerous journeys here where they can die from the elements or even be raped and murdered by cartels and smugglers.
>> Yeah sorry bro your mom is actually with me in bed now and she is a nice lady :(
>> The issue that matters to me is becoming your girlfriend. The way you say issues that matter to us is incredibly hot
>> I agree, they just letting any and everybody in. Dont matter if their pedophiles or murders
>> Nah, screw these guys.
>> Ok go pick 🍅 in a hot field or work at an AC Office
>> It's not important to me to be respectful, that's where we differ. Screw these guys.
>> IM A FERAL GIRL

tox_austin_b
>> i think u should suck a dick
>> Clueless fucking liberals don't get it
>> We need to stop encouraging illegal immigration; it causes migrants to take dangerous journeys here where they can die from the elements or even be raped and murdered by cartels and smugglers.
>> I am not just pro death penalty, I think we should add a torture penalty on top of it. The real scum of the world should be tortured as they await their eventual death.
>> A border wall is the stupidest idea from a traitor scamming orange person with fake hair named Donold
>> Why is it that people living in a country founded by immigrants are so against immigration? It's like "" I got mine, screw you""
>> American citizens are dumb for thinking their guns would be enough to stop an authoritarian government
>> It's not important to me to be respectful, that's where we differ. Screw these guys.
>> Way to paint brush and fucking label people
>> . Any idiot can use a military style weapon to spray bullets uncontrolled and do serious damage. While a regular gun can still cause harm, I’d argue it would require more skill to devastate a mass population. There would also be a greater chance of stopping a lone gunmen.

In [5]:
post_info[['ih_austin_a','ih_austin_b','tox_austin_a','tox_austin_b']].corr()

              ih_austin_a  ih_austin_b  tox_austin_a  tox_austin_b
ih_austin_a      1.000000     0.934668     -0.317300     -0.284845
ih_austin_b      0.934668     1.000000     -0.251984     -0.228471
tox_austin_a    -0.317300    -0.251984      1.000000      0.978241
tox_austin_b    -0.284845    -0.228471      0.978241      1.000000

# IH Post Setup

In [6]:
ih_posts = ["A lot of reporting I've seen suggests that the illegal crossing are very dangerous. If that's true, we should do everything we can to deter this. I've heard that many die every year crossing in unsafe areas, and that even when they make it across they die of heat and thrust or crammed in the back of trucks. It seems like, then, a border wall is for their safety as well as ours.",
            "I get the reason some people want gun control.  I want them to understand that where I live, we need guns. We are over run with coyotes. They kill our pets. We try and kill them. You have to use a weapon with range. What youd call an assault weapon is perfect for that, and they are popular here for coyotes. I just scare them with my gun, because I don't ever hit them",
            "I might be wrong but it seems like the places that have the most mayhem are those with the most restrictive laws. I think about the pressure cooker bombs a few years back at the marathon.",
            "I totally understand, it's not the guns fault. We shouldn't do away with guns because of recent incidents, but it seems to me that we need to look at those who use the guns. I think regulating who can get access to them could help solve this issue. I agree that people have the need to feel safe and they should secure their environment the way they feel comfortable",
            "I try not to be naive that utopia exists or can exist. I know some people think differently, but I do believe in laws and rules and that people are basically good and follow them most of the time. I'd love to see data on this, but I feel like it's only the fringe that does not follow them and causes mayhem for the rest of us.",
            "I understand it is a complex issue and I actually have no problem with asylum seekers. I personally believe that we should be letting in people who will come in to this country the legal way and assimilate into our country. This is just my perspective and open to hear the views of others.",
            "I understand why people are worried about the Southern Border situation, but I don't think that has much to do with terrorism. I might be wrong, but I think that more terrorists are coming over the Canadian border.",
            "I understand why some people want  gun control.  It would help insure guns aren't  given to unstable people. But I also believe that as an American I have every right to defend my property, family, and myself with a gun or guns. I worry only criminals would have weapons.",
            "I'm honestly curious about what the other side thinks. I agree that the gangs and the drugs that come over here from Mexico are a problem. At the same time,  I think we already have gangs and drugs over here before Mexico brought them over.",
            "I'm no psychologist, but I don't think that criminals care what the laws are and what they can or can't do. If that is true, they will obtain a gun by whatever means they can, carry it illegally, use it in a crime and possibly use it to rob you.",
            "I'm not an expert on gun policy, but I did write research papers on the topic in college. While doing research, I was persuaded there was a lot misinformation put out by the NRA, which wa led by someone personally enriching himself from the sales of ammunition.",
            "I'm open to hearing other views, but it sure seems like gun control doesn't work. I've heard that the states with the strictest gun control has the highest crime rates and murder rates. I would think that's because only criminal have the guns.",
            "I'm sure others disagree, but I don't think it's our responsibility as a nation to take care of people from other countries who can't get any help from their own government. I think we have enough AMERICANS who need assistance, and we should help them first. I guess I just don't understand why we should be paying for anyone who manages to sneak in to our country.",
            "It's been a long time since I took US history, but I believe this land as far as Texas, New Mexico, Arizona, California, we're all Mexico territory before The United States took it from them. So I guess it would make sense that They're going to come back, maybe because they never left.",
            "Living close to the border has made me think that we need a wall. Our border patrol, who are the real experts, has asked for a wall. I haven't dug into the numbers, but I've heard the wall has already made in a difference in the areas it is in place. I feel we shouldn't ask our border patrol to risk their lives and not give them the tools they ask for.",
            "Others might disagree, but I don't understand the argument that  Mexicans are taking jobs.  If you are unemployed, couldn't find a job anywhere, and a lettuce field in your city that was hiring, would you apply? My sense is that most Americans would say no.",
            "Others might disagree, but I think we need reasonable and uniform NATIONAL gun legislation. I think one reason for the failure of gun control laws in the US is the pathwork of state-to-state differences. I might be wrong, but I think Congress even forbid the government trackingof gun violence deaths.",
            "I'm not an expert, but it seems like more immigration can only hurt me. I'm interesting in hearing the argument for the other side.",
            "I understand the argument that the system needs reform. However, my own view is that many who have immigrated are the epitome of an outstanding citizens that contributes to society and our economy.",
            "I'm open to other ideas, but I wonder if we should require every gun sale to be registered and require gun manufacturers to include trigger locks at no additional charge to the consumer.  It probably won't solve all our problems, but I think that we can take measures to reduce gun deaths without trampling on the 2nd Amendment."]

In [7]:
all_posts = pd.read_csv("participant_content.csv")
all_posts = all_posts[all_posts.userContent == 0]

In [8]:
ih = []

for p in ih_posts:
    ids = list(all_posts[all_posts.postOrCommentText.apply(lambda x: x == p)].postOrCommentId)
    if len(ids) == 0:
        print(p)
    ih += ids

ih

['654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb55f',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '654e2eccf18dbd001f7ab0a8',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb59c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae8f1c1b5001f5cb3d7',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae7f1c1b5001f5cb33f',
 '655d0ae8f1c1b5001f5cb3d7',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '655d0ae7f1c1b5001f5cb33f',
 '654e2eccf18dbd001f7ab05c',
 '655d0ae7f1c1b5001f5cb345',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',
 '654e2eccf18dbd001f7ab05c',

# Lib/Con Post Setup

In [9]:
lib_posts = [
"I understand why people are worried about the Southern Border situation, but I don't think that has much to do with terrorism. I might be wrong, but I think that more terrorists are coming over the Canadian border.",
"Others might disagree, but I don't understand the argument that  Mexicans are taking jobs.  If you are unemployed, couldn't find a job anywhere, and a lettuce field in your city that was hiring, would you apply? My sense is that most Americans would say no.",
"It's been a long time since I took US history, but I believe this land as far as Texas, New Mexico, Arizona, California, we're all Mexico territory before The United States took it from them. So I guess it would make sense that They're going to come back, maybe because they never left.",
"Others might disagree, but I think we need reasonable and uniform NATIONAL gun legislation. I think one reason for the failure of gun control laws in the US is the pathwork of state-to-state differences. I might be wrong, but I think Congress even forbid the government trackingof gun violence deaths.",
"I'm open to other ideas, but I wonder if we should require every gun sale to be registered and require gun manufacturers to include trigger locks at no additional charge to the consumer.  It probably won't solve all our problems, but I think that we can take measures to reduce gun deaths without trampling on the 2nd Amendment.",
"The problem is not guns; it's the people who have them. I know lots of people that I'd be comfortable having any type of gun. We need to restrict gun possession to responsible people - not drunks, or wife-beaters, not white supremesists. And not political extremeidts. Pretty obvious.",
"Background checks will stop some people who should not own guns from owning them and that's a start. We have finance laws we know people will break but we still do what we can to try to police it.",
"We need mandatory training, licensing, and spaces where guns are and are not allowed.",
"We live in a society and pay taxes and agree to social norms for protection. We do not live in the world as independent, armed encampments. It may cost me or a loved one our lives, but, living gun-free is the price for a civilized society.",
"We need stricter gun laws for modern times. At this point people don't need the right to bare arms. As a civilization, we've moved past this primal state. Our laws need a reality makeover.",
"I say yes to gun control. We must stand up to the NRA!",
"Stricter gun laws would help in many situations. It would definitely help decrease the incidence of gun violence. No one is saying that people will not be able to buy/own guns anymore. The government is not taking away your right to bear arms, it would just make it harder for those who may not be fit to own a gun to buy one.",
"Military weapons should not be sold to the public. No one that isn't in the military needs an AK-47 or similar weapon. These types of weapons were specifically created for war and not for public use or entertainment.",
"There should be gun bans even though gun enthusiasts will riot in response.",
"A good guy with a gun can kill a bad guy with a gun, but what if there were no guns at all? Protection and security should be left to law enforcement.",
"Automatic rifles need to be illegal.",
"If gun control means gun ban, then yes. Though I'm all for registration.",
"I am for gun control: ban them in the US unless there are special circumstances to own them.",
"I think gun control will stop all the mass shootings.",
"Guns are dangerous",
"The bottom line is that we benefit from the human capital that comes here legally to grow our economy, to innovate and lend their skills and talent to a country that welcomes them. Tech and finance would absolutely shut down without the H1-B visa program. On the other end of the spectrum, I see undocumented workers cleaning gutters all the time.",
"A wall is an expensive an useless symbolic endeavour that won't actually do anything to stop or slow immigration. 90% of people in this country illegally entered with valid work or tourism visas and then just did not leave when they were supposed to. It's the clogged up immigration court system that leads to undocumented immigrants more than an unsecured border.",
"Illegal immigrants do pay taxes. There is a tax id number specifically for illegal immigrants. Everyone pays sales tax at checkout for groceries etc. Unless you are homeless you pay rent or own a home. Part of that is paying school and property taxes.",
"Many farms in the past years have had significant waste due to a shortage of labor not being able to harvest. This increases food prices. The largest shortage of labor in healthcare is in nursing home jobs and home health aids. Immigrants frequently fill these jobs.",
"My view is that benefits of immigration outweigh the harm, by a lot. We gain smart and able folks. My doctor for the past 10 years was an immigrant, and I really liked the care he gave me. Plus immigrants will sometimes take jobs native born don't want,like house cleaning.",
"Immigrants seem to do more to try and support themselves than many native-born Americans",
"Historically, America is a nation of immigrants. And each group has contributed to the development of our society. Politicians just play on the fears of the working class to build opposition to immigration.",
"In my view, first-generation immigrants are the hardest-working, family-oriented, caring and driven people. Anyone with a heart would be welcoming them into your community. They are not the enemies, whatever their immigration status. They exhibit the values our country holds dear.",
"We need a way to get the labor we need, without exploitation, build community by decriminalizing immigration, and recognize that our country's actions in the world have done a great deal to create the conditions many people who come here are fleeing.",
"Immigration is the reason several countries, such as the United States, exist. Immigrants bring their culture, knowledge, and abilities to the new countries they inhabit.",
"Immigration has always been an integral part of the policy in the USA and should definatly continue.",
"I'm honestly curious about what the other side thinks. I agree that the gangs and the drugs that come over here from Mexico are a problem. At the same time,  I think we already have gangs and drugs over here before Mexico brought them over.",
"I understand the argument that the system needs reform. However, my own view is that many who have immigrated are the epitome of an outstanding citizens that contributes to society and our economy.",
"The US needs immigration in order to meet the economic needs of this country.",
"I believe the benefits of legal immigration outweigh the downsides",
"I'm not an expert on gun policy, but I did write research papers on the topic in college. While doing research, I was persuaded there was a lot misinformation put out by the NRA, which wa led by someone personally enriching himself from the sales of ammunition.",
"I feel that there are certain people that are mentally incapable of handling a gun. There should be some system that helps sift the mentally ill out from those who are capable and able to use a gun appropriately. I'm not sure about the specifics, though...",
"I totally understand, it's not the guns fault. We shouldn't do away with guns because of recent incidents, but it seems to me that we need to look at those who use the guns. I think regulating who can get access to them could help solve this issue. I agree that people have the need to feel safe and they should secure their environment the way they feel comfortable",
]

con_posts = [
"I'm not an expert, but it seems like more immigration can only hurt me. I'm interesting in hearing the argument for the other side.",
"I'm sure others disagree, but I don't think it's our responsibility as a nation to take care of people from other countries who can't get any help from their own government. I think we have enough AMERICANS who need assistance, and we should help them first. I guess I just don't understand why we should be paying for anyone who manages to sneak in to our country.",
"I understand it is a complex issue and I actually have no problem with asylum seekers. I personally believe that we should be letting in people who will come in to this country the legal way and assimilate into our country. This is just my perspective and open to hear the views of others.",
"Living close to the border has made me think that we need a wall. Our border patrol, who are the real experts, has asked for a wall. I haven't dug into the numbers, but I've heard the wall has already made in a difference in the areas it is in place. I feel we shouldn't ask our border patrol to risk their lives and not give them the tools they ask for.",
"A lot of reporting I've seen suggests that the illegal crossing are very dangerous. If that's true, we should do everything we can to deter this. I've heard that many die every year crossing in unsafe areas, and that even when they make it across they die of heat and thrust or crammed in the back of trucks. It seems like, then, a border wall is for their safety as well as ours.",
"Why does it have to be immigrants who forever change the cultural fabric of our country? We should preserve American identity & culture rather than make it a hodgepodge of different sects of world cultures with no overarching identity or commonality.",
"While you can name a handful of brilliant, successful immigrants, they aren't representative of the 1 million we take in each year. We should drastically reduce that number if not decrease it to net zero.",
"We need the border wall. As a country, we need to be able to secure our borders, and I have felt that way for a long time.",
"Our current lack of control over our own borders and outdated immigration laws have not served us well lately (nor even served the immigrants themselves well). We need to update our immigration laws to be more selective, enforce them more consistently, and remove all the illegals within our borders.",
"Illegals clog up the welfare office, free clinics, YMCA, ect. Without paying any taxes that support these things. Also they tend to have children soon as they get here making it impossible to deport them as the child is concidered an amercian.",
"We should require immigrants tto meet the same ideals we had in the 50's. My parents had to learn the language, pass a test and have a reason to be here and for my Dad that was a job that required education. The biggest problem I think we have is the sheer numbers of undocumented immigrants.",
"The immigration needs to be controlled in order to maintain any semblance of national identity. Past immigrants came to be a part of the great United States, to become part of us. They would embrace our culture and values and contribute theirs to make us all better. If the influx of immigrants is uncontrolled we run the risk of losing that unified goal.",
"Immigrants just come to get what they can, to take the opportunities living here affords without really investing energy and emotion into becoming an American. This further promotes divisions among us as different cultures just gather in various areas, re-establishing pockets of their own culture, rather than assimilating into ours",
"Immigration was good when they came and assimilated to the country's core values",
"Immigration is dangerous",
"I think its crazy to insist teachers learn spanish to teach illegals",
"I don't support immigration if people are coming here illegally",
"Crime rates are lower among illegals then citizens because there are more citizens then illegals.",
"I might be wrong but it seems like the places that have the most mayhem are those with the most restrictive laws. I think about the pressure cooker bombs a few years back at the marathon.",
"I try not to be naive that utopia exists or can exist. I know some people think differently, but I do believe in laws and rules and that people are basically good and follow them most of the time. I'd love to see data on this, but I feel like it's only the fringe that does not follow them and causes mayhem for the rest of us.",
"I'm no psychologist, but I don't think that criminals care what the laws are and what they can or can't do. If that is true, they will obtain a gun by whatever means they can, carry it illegally, use it in a crime and possibly use it to rob you.",
"I understand why some people want  gun control.  It would help insure guns aren't  given to unstable people. But I also believe that as an American I have every right to defend my property, family, and myself with a gun or guns. I worry only criminals would have weapons.",
"I'm open to hearing other views, but it sure seems like gun control doesn't work. I've heard that the states with the strictest gun control has the highest crime rates and murder rates. I would think that's because only criminal have the guns.",
'''Folks say ""those who are a threat"" shouldn't have guns. Felons -- even white-collar, non-violent felons who have done their time, are denied forever the right to own or possess a gun. I don't think we should strip those rights forever.''',
"It's impossible to control illegal gun sales, just like illegal drugs on the streets. If the bad people want them, they will get them. But the people who typically get them for good intentions are to protect themselves against the bad people with bad intentions so it just comes full circle. Guns should be for protections against the bad but now the bad includes people with guns.",
"Gun control will not stop criminals from getting black market guns.",
"Not one mass murderer was an NRA member. Why is that? Did you know the NRA is the oldest civil rights organization in America?",
"Our 2nd amendment right separates us from every country out there. It was derived out of tyranny not hunting or target shooting. It was the 2nd ammendment after free speech. It was that important.",
"I get the reason some people want gun control.  I want them to understand that where I live, we need guns. We are over run with coyotes. They kill our pets. We try and kill them. You have to use a weapon with range. What youd call an assault weapon is perfect for that, and they are popular here for coyotes. I just scare them with my gun, because I don't ever hit them",
"A little history will do you alot of good. Facts of history are not something someone made up, they are facts. Just like the fact vaccines help us fight disease, so a good guy trained with a gun is better than an unprepared bad guy.  With proper training guns are safer than you driving while texting.",
"The 2nd amendment is to ward off tyrannical governments. What does China, North Korea and Nazi Germany have in common. Citizens couldn't and still can't defend themselves when their governments get out of hand. I'd rather have the 2A then not.",
"I believe in in being cautious, but at what cost? It just seems like everyone wants to start taking our rights away. I hope that we don't lose the right to protect our families and friends.",
"The 2nd Amendmentwas to prevent , from invasion and Tyrrany- They first thing the enemy want is your weapons!",
"I think guns law are already strick enough.",
"No more gun control. Just enforce the laws that are ALREADY in place.",
"The 2nd amendment protects my rights and shall not be infringed upon",
"Chicago has some of the strictest gun control laws. That didn't stop the the rising gun related killings.",
"There is no benefit to gun control"
]

In [10]:
lib = []

for p in lib_posts:
    ids = list(all_posts[all_posts.postOrCommentText.apply(lambda x: x == p)].postOrCommentId)
    if len(ids) == 0:
        print(p, '\n')
    lib += ids

lib

['654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb413',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '654e2ecbf18dbd001f7aaef2',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '655d0ae8f1c1b5001f5cb571',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb415',
 '655d0ae8f1c1b5001f5cb56b',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb415',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',
 '654e2ecbf18dbd001f7aaf04',
 '654e2ecbf18dbd001f7aaf04',
 '655d0ae8f1c1b5001f5cb56b',

In [11]:
con = []

for p in con_posts:
    ids = list(all_posts[all_posts.postOrCommentText.apply(lambda x: x == p)].postOrCommentId)
    if len(ids) == 0:
        print(p, '\n')
    con += ids

con

['654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb555',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '654e2eccf18dbd001f7ab25b',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '655d0ae8f1c1b5001f5cb590',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb55d',
 '655d0ae8f1c1b5001f5cb596',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb55d',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',
 '654e2eccf18dbd001f7ab265',
 '654e2eccf18dbd001f7ab265',
 '655d0ae8f1c1b5001f5cb596',

# Get user-level measures

In [12]:
df = post_info[post_info.userContent == 1]
df

,sessionId,treatmentArm,participantCode,profilePicture,firstName,lastName,bio,postOrCommentId,userContent,staticContent,...,INSULT_EXPERIMENTAL,PROFANITY_EXPERIMENTAL,THREAT_EXPERIMENTAL,SEXUALLY_EXPLICIT,FLIRTATION,perspective_toxicity_agg,ih_austin_a,ih_austin_b,tox_austin_a,tox_austin_b
0,657895d16d158d001f181302,imm_pc,zf1er9,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Ginger,NaN,I love cats!,657897906d158d001f182280,1,0,...,0.127028,0.077732,0.010784,0.038217,0.340470,0.128365,0.469136,0.438154,0.254629,0.120118
1,657895d16d158d001f181302,imm_pc,zf1er9,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Ginger,NaN,I love cats!,657899146d158d001f1856cc,1,0,...,0.033460,0.017778,0.006965,0.006812,0.556122,0.110948,0.351996,0.417278,0.150481,0.061872
2,657895d16d158d001f181302,imm_pc,zf1er9,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Ginger,NaN,I love cats!,657899606d158d001f1862d5,1,0,...,0.007513,0.011714,0.006848,0.006193,0.241154,0.035897,0.459829,0.369664,0.010807,0.006681
3,657896b96d158d001f181516,imm_treat,8gch37,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Yelena22,NaN,NC girl,657898246d158d001f18395d,1,0,...,0.248355,0.045670,0.006965,0.009672,0.299508,0.150781,0.342446,0.345526,0.309935,0.170582
4,657896b96d158d001f181516,imm_treat,8gch37,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Yelena22,NaN,NC girl,657899456d158d001f185f72,1,0,...,0.007969,0.010502,0.006045,0.003052,0.224278,0.033593,0.382053,0.364194,0.012817,0.006676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4389,657b61122855e7001f93f0ef,imm_control3,pqdpcp,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Cbros,NaN,Baba,657b62628b12dc001f05d62b,1,0,...,0.027089,0.019554,0.008117,0.004954,0.225375,0.067105,0.128559,0.156050,0.142560,0.057711
4390,657b64a78b12dc001f06215b,imm_control3,h63zav,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Shan,NaN,"Jersey girl, born and raised!!! I love animals...",657b65a88b12dc001f069f70,1,0,...,0.035223,0.032894,0.033732,0.014331,0.453156,0.096431,0.093467,0.090807,0.172851,0.056027
4391,657b64a78b12dc001f06215b,imm_control3,h63zav,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Shan,NaN,"Jersey girl, born and raised!!! I love animals...",657b66162855e7001f9554e3,1,0,...,0.012605,0.015147,0.007806,0.008434,0.351283,0.055717,0.548232,0.509349,0.032156,0.015593
4392,657b64a78b12dc001f06215b,imm_control3,h63zav,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Shan,NaN,"Jersey girl, born and raised!!! I love animals...",657b66cb8b12dc001f07eca7,1,0,...,0.012377,0.010314,0.006654,0.003155,0.388082,0.056238,0.284360,0.376801,0.024496,0.010128
4393,657b64a78b12dc001f06215b,imm_control3,h63zav,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Shan,NaN,"Jersey girl, born and raised!!! I love animals...",657b670e8b12dc001f085097,1,0,...,0.063899,0.025907,0.028379,0.007461,0.290690,0.116695,0.111967,0.118499,0.270478,0.121585

# Aggregate to User-level Measures

In [13]:
# Aggregate all posts

agg_all = df.groupby('participantCode').agg(
    
    # IH A
    ih_a_all = pd.NamedAgg(column="ih_austin_a", aggfunc="mean"),
    
    # IH B
    ih_b_all = pd.NamedAgg(column="ih_austin_b", aggfunc="mean"),

    #Toxicitiy A
    tox_a_all = pd.NamedAgg(column="tox_austin_a", aggfunc="mean"),

    # Toxicity B
    tox_b_all = pd.NamedAgg(column="tox_austin_b", aggfunc="mean")
).reset_index()

agg_all

     participantCode  ih_a_all  ih_b_all  tox_a_all  tox_b_all
0             114n66  0.266236  0.296404   0.048334   0.019166
1             11b468  0.252210  0.323695   0.195428   0.119362
2             11frdz  0.260360  0.285371   0.108976   0.053299
3             11g3d4  0.085161  0.100888   0.028385   0.011247
4             11uby7  0.252306  0.320688   0.093492   0.035447
...              ...       ...       ...        ...        ...
1440          zxyz1h  0.254910  0.228662   0.166437   0.072189
1441          zy6tqc  0.368552  0.346448   0.055111   0.023966
1442          zywuwt  0.211234  0.208270   0.107075   0.052506
1443          zzmpme  0.251089  0.288543   0.110680   0.044659
1444          zzn3e8  0.359929  0.339633   0.122698   0.051915

[1445 rows x 5 columns]

In [14]:
# Aggregate all original posts

df_op = df[pd.isnull(df.parentPost)]

agg_op = df_op.groupby('participantCode').agg(
    
    # IH A
    ih_a_op = pd.NamedAgg(column="ih_austin_a", aggfunc="mean"),
    
    # IH B
    ih_b_op = pd.NamedAgg(column="ih_austin_b", aggfunc="mean"),

    #Toxicitiy A
    tox_a_op = pd.NamedAgg(column="tox_austin_a", aggfunc="mean"),

    # Toxicity B
    tox_b_op = pd.NamedAgg(column="tox_austin_b", aggfunc="mean")
    
).reset_index()

agg_op

     participantCode   ih_a_op   ih_b_op  tox_a_op  tox_b_op
0             114n66  0.343366  0.384123  0.078460  0.030371
1             11b468  0.364973  0.453152  0.063027  0.024358
2             11frdz  0.522249  0.582540  0.051069  0.023632
3             11g3d4  0.085161  0.100888  0.028385  0.011247
4             11uby7  0.313038  0.375686  0.084791  0.033744
...              ...       ...       ...       ...       ...
1290          zxyz1h  0.183477  0.187207  0.237751  0.112069
1291          zy6tqc  0.350682  0.349470  0.054770  0.022682
1292          zywuwt  0.213981  0.240642  0.026028  0.011414
1293          zzmpme  0.251089  0.288543  0.110680  0.044659
1294          zzn3e8  0.588702  0.627878  0.026617  0.010633

[1295 rows x 5 columns]

In [17]:
# Aggregate all comments

df_comm = df[pd.notnull(df.parentPost)]

agg_comm = df_comm.groupby('participantCode').agg(
    
    # IH A
    ih_a_comm = pd.NamedAgg(column="ih_austin_a", aggfunc="mean"),
    
    # IH B
    ih_b_comm = pd.NamedAgg(column="ih_austin_b", aggfunc="mean"),

    #Toxicitiy A
    tox_a_comm = pd.NamedAgg(column="tox_austin_a", aggfunc="mean"),

    # Toxicity B
    tox_b_comm = pd.NamedAgg(column="tox_austin_b", aggfunc="mean"),

    # Number of Comments
    num_messages_comm =pd.NamedAgg(column="tox_austin_a", aggfunc="size")
    
).reset_index()

agg_comm

,participantCode,ih_a_comm,ih_b_comm,tox_a_comm,tox_b_comm,num_messages_comm
0,114n66,0.256594,0.285439,0.044568,0.017766,8
1,11b468,0.195829,0.258967,0.261628,0.166864,2
2,11frdz,0.173064,0.186315,0.128279,0.063189,3
3,11uby7,0.191574,0.265690,0.102193,0.037150,1
4,12ad6y,0.396042,0.347071,0.021909,0.011133,2
...,...,...,...,...,...,...
1261,zx37ux,0.333937,0.323493,0.108110,0.055151,3
1262,zxyz1h,0.271394,0.238228,0.149980,0.062987,13
1263,zy6tqc,0.376210,0.345153,0.055256,0.024516,7
1264,zywuwt,0.209861,0.192083,0.147598,0.073052,2
1265,zzn3e8,0.283671,0.243551,0.154725,0.065675,3

In [20]:
# Aggregate all comments on IH posts

df_ih = df[[i in ih for i in df.parentPost]]

agg_ih = df_ih.groupby('participantCode').agg(
    
    # IH A
    ih_a_ih = pd.NamedAgg(column="ih_austin_a", aggfunc="mean"),
    
    # IH B
    ih_b_ih = pd.NamedAgg(column="ih_austin_b", aggfunc="mean"),

    #Toxicitiy A
    tox_a_ih = pd.NamedAgg(column="tox_austin_a", aggfunc="mean"),

    # Toxicity B
    tox_b_ih = pd.NamedAgg(column="tox_austin_b", aggfunc="mean"),

    # Number of IH Comments
    num_messages_ih =pd.NamedAgg(column="tox_austin_a", aggfunc="size")
    
).reset_index()

agg_ih

    participantCode   ih_a_ih   ih_b_ih  tox_a_ih  tox_b_ih  num_messages_ih
0            11frdz  0.173064  0.186315  0.128279  0.063189                3
1            17xpyv  0.186691  0.240587  0.093515  0.036837                1
2            1bqxnq  0.485825  0.395289  0.010116  0.006244                1
3            1c87zz  0.620381  0.611986  0.008168  0.005664                1
4            1f4cwc  0.437144  0.467190  0.172625  0.093962                2
..              ...       ...       ...       ...       ...              ...
288          zu9wre  0.479444  0.392881  0.006220  0.004736                1
289          zvf1ru  0.475079  0.387230  0.011498  0.006916                1
290          zwphpx  0.161204  0.174138  0.041157  0.016532                5
291          zy6tqc  0.259986  0.316250  0.060258  0.024493                1
292          zzn3e8  0.354583  0.290526  0.190088  0.085176                2

[293 rows x 6 columns]

In [21]:
# Aggregate all comments on Lib posts

df_lib = df[[i in lib for i in df.parentPost]]

agg_lib = df_lib.groupby('participantCode').agg(
    
    # IH A
    ih_a_lib = pd.NamedAgg(column="ih_austin_a", aggfunc="mean"),
    
    # IH B
    ih_b_lib = pd.NamedAgg(column="ih_austin_b", aggfunc="mean"),

    #Toxicitiy A
    tox_a_lib = pd.NamedAgg(column="tox_austin_a", aggfunc="mean"),

    # Toxicity B
    tox_b_lib = pd.NamedAgg(column="tox_austin_b", aggfunc="mean")
    
).reset_index()

agg_lib

    participantCode  ih_a_lib  ih_b_lib  tox_a_lib  tox_b_lib
0            11b468  0.250499  0.330831   0.052058   0.021877
1            11frdz  0.130030  0.127749   0.322361   0.161132
2            12cpx2  0.165415  0.162022   0.106985   0.035733
3            16rhru  0.305004  0.306038   0.095677   0.034662
4            1art8b  0.172380  0.216609   0.031213   0.012253
..              ...       ...       ...        ...        ...
465          zwcmc7  0.445385  0.367337   0.010179   0.007561
466          zwphpx  0.487332  0.395040   0.007571   0.005732
467          zxyz1h  0.394786  0.323643   0.016147   0.010115
468          zy6tqc  0.480017  0.420835   0.012817   0.006992
469          zywuwt  0.129048  0.118807   0.282002   0.138659

[470 rows x 5 columns]

In [22]:
# Aggregate all comments on Con posts

df_con = df[[i in con for i in df.parentPost]]

agg_con = df_con.groupby('participantCode').agg(
    
    # IH A
    ih_a_con = pd.NamedAgg(column="ih_austin_a", aggfunc="mean"),
    
    # IH B
    ih_b_con = pd.NamedAgg(column="ih_austin_b", aggfunc="mean"),

    #Toxicitiy A
    tox_a_con = pd.NamedAgg(column="tox_austin_a", aggfunc="mean"),

    # Toxicity B
    tox_b_con = pd.NamedAgg(column="tox_austin_b", aggfunc="mean")
    
).reset_index()

agg_con

    participantCode  ih_a_con  ih_b_con  tox_a_con  tox_b_con
0            11b468  0.141159  0.187104   0.471199   0.311851
1            11frdz  0.194581  0.215597   0.031238   0.014217
2            11uby7  0.191574  0.265690   0.102193   0.037150
3            12cpx2  0.393745  0.351364   0.111618   0.050148
4            17xpyv  0.186691  0.240587   0.093515   0.036837
..              ...       ...       ...        ...        ...
500          zv3m1r  0.184460  0.190587   0.157564   0.072751
501          zwphpx  0.160355  0.172953   0.041902   0.016833
502          zxyz1h  0.138838  0.130494   0.332537   0.135658
503          zy6tqc  0.259986  0.316250   0.060258   0.024493
504          zzn3e8  0.283671  0.243551   0.154725   0.065675

[505 rows x 5 columns]

In [23]:
# Combine the aggregated data

content_df = agg_all

for agg in [agg_op, agg_comm, agg_ih, agg_con, agg_lib]:
    content_df = content_df.merge(agg, on='participantCode', how="left")

content_df = content_df

content_df

,participantCode,ih_a_all,ih_b_all,tox_a_all,tox_b_all,ih_a_op,ih_b_op,tox_a_op,tox_b_op,ih_a_comm,...,tox_b_ih,num_messages_ih,ih_a_con,ih_b_con,tox_a_con,tox_b_con,ih_a_lib,ih_b_lib,tox_a_lib,tox_b_lib
0,114n66,0.266236,0.296404,0.048334,0.019166,0.343366,0.384123,0.078460,0.030371,0.256594,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11b468,0.252210,0.323695,0.195428,0.119362,0.364973,0.453152,0.063027,0.024358,0.195829,...,NaN,NaN,0.141159,0.187104,0.471199,0.311851,0.250499,0.330831,0.052058,0.021877
2,11frdz,0.260360,0.285371,0.108976,0.053299,0.522249,0.582540,0.051069,0.023632,0.173064,...,0.063189,3.0,0.194581,0.215597,0.031238,0.014217,0.130030,0.127749,0.322361,0.161132
3,11g3d4,0.085161,0.100888,0.028385,0.011247,0.085161,0.100888,0.028385,0.011247,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11uby7,0.252306,0.320688,0.093492,0.035447,0.313038,0.375686,0.084791,0.033744,0.191574,...,NaN,NaN,0.191574,0.265690,0.102193,0.037150,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,zxyz1h,0.254910,0.228662,0.166437,0.072189,0.183477,0.187207,0.237751,0.112069,0.271394,...,NaN,NaN,0.138838,0.130494,0.332537,0.135658,0.394786,0.323643,0.016147,0.010115
1441,zy6tqc,0.368552,0.346448,0.055111,0.023966,0.350682,0.349470,0.054770,0.022682,0.376210,...,0.024493,1.0,0.259986,0.316250,0.060258,0.024493,0.480017,0.420835,0.012817,0.006992
1442,zywuwt,0.211234,0.208270,0.107075,0.052506,0.213981,0.240642,0.026028,0.011414,0.209861,...,NaN,NaN,NaN,NaN,NaN,NaN,0.129048,0.118807,0.282002,0.138659
1443,zzmpme,0.251089,0.288543,0.110680,0.044659,0.251089,0.288543,0.110680,0.044659,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1444,zzn3e8,0.359929,0.339633,0.122698,0.051915,0.588702,0.627878,0.026617,0.010633,0.283671,...,0.085176,2.0,0.283671,0.243551,0.154725,0.065675,NaN,NaN,NaN,NaN

# Merge with Participant Data

In [24]:
user_df = pd.read_csv("Cleaned_study_data.csv")

In [25]:
posit = {'Strongly agree': "lib",
         "Agree": "lib",
          'Somewhat agree': "lib",
          'Neither agree nor disagree': np.nan,
          'Somewhat disagree': "con",
         "Disagree": "con",
          'Strongly disagree': "con"}

def posit_func(x):
    if x.topic == "gun control":
        return posit[x.pre_policy_gc]
    elif x.topic == "immigration":
        return posit[x.pre_policy_imm]

user_df['posit'] = user_df.apply(posit_func,axis=1)

user_df[['posit','pre_policy_imm','pre_policy_gc',"topic"]]

     posit              pre_policy_imm      pre_policy_gc        topic
0      lib                       Agree     Strongly agree  immigration
1      con              Strongly agree  Strongly disagree  gun control
2      con           Strongly disagree     Strongly agree  immigration
3      lib              Somewhat agree     Strongly agree  gun control
4      con                    Disagree     Somewhat agree  immigration
...    ...                         ...                ...          ...
1038   lib              Somewhat agree              Agree  immigration
1039   lib              Strongly agree     Strongly agree  immigration
1040   NaN  Neither agree nor disagree              Agree  immigration
1041   lib                    Disagree     Strongly agree  gun control
1042   lib              Strongly agree  Strongly disagree  immigration

[1043 rows x 4 columns]

In [26]:
len(set(user_df.participant_code))

1043

In [27]:
new_df = content_df.merge(user_df, left_on="participantCode", right_on="participant_code", how="right", validate="1:1")
new_df = new_df.drop(columns=['participantCode'])
new_df

,ih_a_all,ih_b_all,tox_a_all,tox_b_all,ih_a_op,ih_b_op,tox_a_op,tox_b_op,ih_a_comm,ih_b_comm,...,mc_correct,n_op,n_comments,zip_state_match,speeder,commented,posted,passcode,gold_star,posit
0,0.361823,0.348515,0.133737,0.070089,0.360970,0.335827,0.078460,0.033009,0.362249,0.354860,...,1,1,2,1,0,1,1,True,0,lib
1,0.362019,0.410255,0.085755,0.031098,0.512410,0.554325,0.057006,0.020452,0.211628,0.266185,...,1,1,1,1,1,1,1,True,1,con
2,0.383066,0.322223,0.009911,0.006789,0.267132,0.233647,0.013194,0.008441,0.499001,0.410800,...,1,1,1,1,1,1,1,True,1,con
3,0.282872,0.349636,0.096769,0.038011,0.379054,0.458685,0.100023,0.039186,0.186691,0.240587,...,1,1,1,1,1,1,1,True,1,lib
4,0.425425,0.437438,0.051341,0.021750,0.256750,0.272360,0.091122,0.035728,0.594101,0.602517,...,1,1,1,1,1,1,1,True,1,con
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,0.235552,0.223638,0.035396,0.015886,0.220500,0.228770,0.051316,0.018822,0.238562,0.222612,...,1,1,5,1,1,1,1,True,1,lib
1039,0.383666,0.378626,0.028399,0.013212,NaN,NaN,NaN,NaN,0.383666,0.378626,...,1,0,4,1,1,0,1,True,0,lib
1040,0.177561,0.166600,0.024242,0.011742,0.106842,0.112467,0.030388,0.013307,0.248280,0.220734,...,1,1,1,1,1,1,1,True,1,NaN
1041,0.395352,0.387153,0.038950,0.016728,0.299257,0.251120,0.096552,0.039512,0.414571,0.414359,...,1,1,5,1,1,1,1,True,1,lib
1042,0.329476,0.324288,0.071657,0.030755,0.135998,0.191204,0.011749,0.006911,0.361722,0.346469,...,1,1,6,1,1,1,1,True,1,lib

In [28]:
len(set(new_df.participant_code))

1043

In [29]:
data = []

for ind, row in new_df.iterrows():
    datum = {"participantCode": row['participant_code']}

    if row.posit == "lib":

        # IH A
        datum['ih_a_ca'] = row.ih_a_con
        
        # IH B
        datum['ih_b_ca'] = row.ih_b_con
    
        #Toxicitiy A
        datum['tox_a_ca'] = row.tox_a_con
    
        # Toxicity B
        datum['tox_b_ca'] = row.tox_b_con

    elif row.posit == "con":
        
        # IH A
        datum['ih_a_ca'] = row.ih_a_lib
        
        # IH B
        datum['ih_b_ca'] = row.ih_b_lib
    
        #Toxicitiy A
        datum['tox_a_ca'] = row.tox_a_lib
    
        # Toxicity B
        datum['tox_b_ca'] = row.tox_b_lib

    data.append(datum)

ca_df = pd.DataFrame(data)
ca_df

     participantCode   ih_a_ca   ih_b_ca  tox_a_ca  tox_b_ca
0             8gch37  0.382053  0.364194  0.012817  0.006676
1             nyuhem       NaN       NaN       NaN       NaN
2             gw6r7f       NaN       NaN       NaN       NaN
3             17xpyv  0.186691  0.240587  0.093515  0.036837
4             hfyv7m       NaN       NaN       NaN       NaN
...              ...       ...       ...       ...       ...
1038          r9hyrv  0.244652  0.229313  0.035145  0.015861
1039          3naupc  0.343404  0.298406  0.010430  0.006796
1040          6fxpk1       NaN       NaN       NaN       NaN
1041          pwghnt  0.192040  0.181048  0.027324  0.015055
1042          nbwdbg  0.432726  0.448406  0.180751  0.076329

[1043 rows x 5 columns]

In [30]:
len(set(new_df.participant_code))

1043

In [31]:
new_df = new_df.merge(ca_df, left_on = "participant_code", right_on="participantCode", how="left", validate="1:1").drop(columns="participantCode")

In [32]:
new_df

,ih_a_all,ih_b_all,tox_a_all,tox_b_all,ih_a_op,ih_b_op,tox_a_op,tox_b_op,ih_a_comm,ih_b_comm,...,speeder,commented,posted,passcode,gold_star,posit,ih_a_ca,ih_b_ca,tox_a_ca,tox_b_ca
0,0.361823,0.348515,0.133737,0.070089,0.360970,0.335827,0.078460,0.033009,0.362249,0.354860,...,0,1,1,True,0,lib,0.382053,0.364194,0.012817,0.006676
1,0.362019,0.410255,0.085755,0.031098,0.512410,0.554325,0.057006,0.020452,0.211628,0.266185,...,1,1,1,True,1,con,NaN,NaN,NaN,NaN
2,0.383066,0.322223,0.009911,0.006789,0.267132,0.233647,0.013194,0.008441,0.499001,0.410800,...,1,1,1,True,1,con,NaN,NaN,NaN,NaN
3,0.282872,0.349636,0.096769,0.038011,0.379054,0.458685,0.100023,0.039186,0.186691,0.240587,...,1,1,1,True,1,lib,0.186691,0.240587,0.093515,0.036837
4,0.425425,0.437438,0.051341,0.021750,0.256750,0.272360,0.091122,0.035728,0.594101,0.602517,...,1,1,1,True,1,con,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,0.235552,0.223638,0.035396,0.015886,0.220500,0.228770,0.051316,0.018822,0.238562,0.222612,...,1,1,1,True,1,lib,0.244652,0.229313,0.035145,0.015861
1039,0.383666,0.378626,0.028399,0.013212,NaN,NaN,NaN,NaN,0.383666,0.378626,...,1,0,1,True,0,lib,0.343404,0.298406,0.010430,0.006796
1040,0.177561,0.166600,0.024242,0.011742,0.106842,0.112467,0.030388,0.013307,0.248280,0.220734,...,1,1,1,True,1,NaN,NaN,NaN,NaN,NaN
1041,0.395352,0.387153,0.038950,0.016728,0.299257,0.251120,0.096552,0.039512,0.414571,0.414359,...,1,1,1,True,1,lib,0.192040,0.181048,0.027324,0.015055
1042,0.329476,0.324288,0.071657,0.030755,0.135998,0.191204,0.011749,0.006911,0.361722,0.346469,...,1,1,1,True,1,lib,0.432726,0.448406,0.180751,0.076329

In [33]:
len(set(new_df.participant_code))

1043

In [35]:
new_df.to_csv("PerspectiveOutcomes.csv", index=False)

# Let the Mining Begin!

In [37]:
new_df.columns.to_list()

['participantCode',
 'ih_a_all',
 'ih_b_all',
 'tox_a_all',
 'tox_b_all',
 'ih_a_op',
 'ih_b_op',
 'tox_a_op',
 'tox_b_op',
 'ih_a_comm',
 'ih_b_comm',
 'tox_a_comm',
 'tox_b_comm',
 'ih_a_ih',
 'ih_b_ih',
 'tox_a_ih',
 'tox_b_ih',
 'ih_a_con',
 'ih_b_con',
 'tox_a_con',
 'tox_b_con',
 'ih_a_lib',
 'ih_b_lib',
 'tox_a_lib',
 'tox_b_lib',
 'StartDate_post',
 'EndDate_post',
 'Status_post',
 'IPAddress_post',
 'Progress_post',
 'Duration (in seconds)_post',
 'Finished_post',
 'RecordedDate_post',
 'ResponseId_post',
 'RecipientLastName_post',
 'RecipientFirstName_post',
 'RecipientEmail_post',
 'ExternalReference_post',
 'LocationLatitude_post',
 'LocationLongitude_post',
 'DistributionChannel_post',
 'UserLanguage_post',
 'timer.panas_First Click',
 'timer.panas_Last Click',
 'timer.panas_Page Submit',
 'timer.panas_Click Count',
 'panas_active',
 'panas_attentive',
 'panas_alert',
 'panas_determined',
 'panas_inspired',
 'panas_hostile',
 'panas_ashamed',
 'panas_upset',
 'panas_afraid',
 'panas_nervous',
 'timer.desc.users_First Click',
 'timer.desc.users_Last Click',
 'timer.desc.users_Page Submit',
 'timer.desc.users_Click Count',
 'desc_users_polite',
 'desc_users_aggressive',
 'desc_users_tolerant',
 'timer.desc.exp_First Click',
 'timer.desc.exp_Last Click',
 'timer.desc.exp_Page Submit',
 'timer.desc.exp_Click Count',
 'desc_platform_engaging',
 'desc_platform_toxic',
 'desc_platform_exhausting',
 'timer.likely.use_First Click',
 'timer.likely.use_Last Click',
 'timer.likely.use_Page Submit',
 'timer.likely.use_Click Count',
 'future_use',
 'timer.comfort_First Click',
 'timer.comfort_Last Click',
 'timer.comfort_Page Submit',
 'timer.comfort_Click Count',
 'comfort_sharing',
 'timer.bots_First Click',
 'timer.bots_Last Click',
 'timer.bots_Page Submit',
 'timer.bots_Click Count',
 'bots',
 'timer.password_First Click',
 'timer.password_Last Click',
 'timer.password_Page Submit',
 'timer.password_Click Count',
 'password',
 'timer.congratz_First Click',
 'timer.congratz_Last Click',
 'timer.congratz_Page Submit',
 'timer.congratz_Click Count',
 'timer.manip.check_First Click',
 'timer.manip.check_Last Click',
 'timer.manip.check_Page Submit',
 'timer.manip.check_Click Count',
 'manip_check',
 'timer.open.badge_First Click',
 'timer.open.badge_Last Click',
 'timer.open.badge_Page Submit',
 'timer.open.badge_Click Count',
 'open_badge',
 'Q104_First Click',
 'Q104_Last Click',
 'Q104_Page Submit',
 'Q104_Click Count',
 'Q105_First Click',
 'Q105_Last Click',
 'Q105_Page Submit',
 'Q105_Click Count',
 'Q106_First Click',
 'Q106_Last Click',
 'Q106_Page Submit',
 'Q106_Click Count',
 'Q107_First Click',
 'Q107_Last Click',
 'Q107_Page Submit',
 'Q107_Click Count',
 'timer.im.policy.post_First Click',
 'timer.im.policy.post_Last Click',
 'timer.im.policy.post_Page Submit',
 'timer.im.policy.post_Click Count',
 'post_policy_1',
 'post_policy_2',
 'timer.therms.post_First Click',
 'timer.therms.post_Last Click',
 'timer.therms.post_Page Submit',
 'timer.therms.post_Click Count',
 'post_therm_1',
 'post_therm_2',
 'timer.ih.post_First Click',
 'timer.ih.post_Last Click',
 'timer.ih.post_Page Submit',
 'timer.ih.post_Click Count',
 'post_ih_1',
 'post_ih_2',
 'post_ih_3',
 'post_ih_4',
 'post_ih_5',
 'post_ih_6',
 'timer.open.end_First Click',
 'timer.open.end_Last Click',
 'timer.open.end_Page Submit',
 'timer.open.end_Click Count',
 'feedback',
 'timer.complete.code_First Click',
 'timer.complete.code_Last Click',
 'timer.complete.code_Page Submit',
 'timer.complete.code_Click Count',
 'participant_code',
 'Party1_post',
 'Party2_post',
 'third_order',
 'panas_neg',
 'panas_pos',
 'panas',
 'StartDate_pre',
 'EndDate_pre',
 'Status_pre',
 'IPAddress_pre',
 'Progress_pre',
 'Duration (in seconds)_pre',
 'Finished_pre',
 'RecordedDate_pre',
 'ResponseId_pre',
 'RecipientLastName_pre',
 'RecipientFirstName_pre',
 'RecipientEmail_pre',
 'ExternalReference_pre',
 'LocationLatitude_pre',
 'LocationLongitude_pre',
 'DistributionChannel_pre',
 'UserLanguage_pre',
 'timer.pol.int_First Click',
 'timer.pol.int_Last Click',
 'timer.pol.int_Page Submit',
 'timer.pol.int_Click Count',
 'political_interest',
 'timer.policy.pre_First Click',
 'timer.policy.pre_Last Click',
 'timer.policy.pre_Page Submit',
 'timer.policy.pre_Click Count',
 'pre_policy_imm',
 'pre_policy_gc',
 'timer.pre.therms_First Click',
 'timer.pre.therms_Last Click',
 'timer.pre.therms_Page Submit',
 'timer.pre.therms_Click Count',
 'pre_therm_1',
 'pre_therm_2',
 'timer.pre.ih_First Click',
 'timer.pre.ih_Last Click',
 'timer.pre.ih_Page Submit',
 'timer.pre.ih_Click Count',
 'pre_ih_1',
 'pre_ih_2',
 'pre_ih_3',
 'pre_ih_4',
 'pre_ih_5',
 'pre_ih_6',
 'timer.zip_First Click',
 'timer.zip_Last Click',
 'timer.zip_Page Submit',
 'timer.zip_Click Count',
 'zip',
 'Q97_First Click',
 'Q97_Last Click',
 'Q97_Page Submit',
 'Q97_Click Count',
 'timer.ob.buttons_First Click',
 'timer.ob.buttons_Last Click',
 'timer.ob.buttons_Page Submit',
 'timer.ob.buttons_Click Count',
 'timer.ob.author_First Click',
 'timer.ob.author_Last Click',
 'timer.ob.author_Page Submit',
 'timer.ob.author_Click Count',
 'timer.ob.status_First Click',
 'timer.ob.status_Last Click',
 'timer.ob.status_Page Submit',
 'timer.ob.status_Click Count',
 'Q111_First Click',
 'Q111_Last Click',
 'Q111_Page Submit',
 'Q111_Click Count',
 'Party1',
 'Party2',
 'topic',
 'treatment_arm',
 'treatment',
 'StartDate',
 'EndDate',
 'Status',
 'IPAddress',
 'Progress',
 'Duration (in seconds)',
 'Finished',
 'RecordedDate',
 'ResponseId',
 'RecipientLastName',
 'RecipientFirstName',
 'RecipientEmail',
 'ExternalReference',
 'LocationLatitude',
 'LocationLongitude',
 'DistributionChannel',
 'UserLanguage',
 'Q_RecaptchaScore',
 'meta_Browser',
 'meta_Version',
 'meta_Operating System',
 'meta_Resolution',
 'timer.consent_First Click',
 'timer.consent_Last Click',
 'timer.consent_Page Submit',
 'timer.consent_Click Count',
 'Consent',
 'timer.platforms_First Click',
 'timer.platforms_Last Click',
 'timer.platforms_Page Submit',
 'timer.platforms_Click Count',
 'platforms_fb',
 'platforms_insta',
 'platforms_tiktok',
 'platforms_x',
 'platforms_truth',
 'platforms_jive',
 'timer.state_First Click',
 'timer.state_Last Click',
 'timer.state_Page Submit',
 'timer.state_Click Count',
 'state',
 'timer.age_First Click',
 'timer.age_Last Click',
 'timer.age_Page Submit',
 'timer.age_Click Count',
 'age',
 'timer.device_First Click',
 'timer.device_Last Click',
 'timer.device_Page Submit',
 'timer.device_Click Count',
 'device',
 'timer.download_First Click',
 'timer.download_Last Click',
 'timer.download_Page Submit',
 'timer.download_Click Count',
 'download_apple',
 'download_android',
 'timer.race_First Click',
 'timer.race_Last Click',
 'timer.race_Page Submit',
 'timer.race_Click Count',
 'race ',
 'timer.image_First Click',
 'timer.image_Last Click',
 'timer.image_Page Submit',
 'timer.image_Click Count',
 'screen_image',
 'timer.pid3_First Click',
 'timer.pid3_Last Click',
 'timer.pid3_Page Submit',
 'timer.pid3_Click Count',
 'pid3',
 'timer.pid.followup_First Click',
 'timer.pid.followup_Last Click',
 'timer.pid.followup_Page Submit',
 'timer.pid.followup_Click Count',
 'pid_strong',
 'pid_lean',
 'timer.ideo_First Click',
 'timer.ideo_Last Click',
 'timer.ideo_Page Submit',
 'timer.ideo_Click Count',
 'ideo7',
 'timer.educ.1_First Click',
 'timer.educ.1_Last Click',
 'timer.educ.1_Page Submit',
 'timer.educ.1_Click Count',
 'educ_1',
 '1',
 'timer.educ.2_First Click',
 'timer.educ.2_Last Click',
 'timer.educ.2_Page Submit',
 'timer.educ.2_Click Count',
 'educ_2',
 '2',
 'timer.educ.3_First Click',
 'timer.educ.3_Last Click',
 'timer.educ.3_Page Submit',
 'timer.educ.3_Click Count',
 'educ_3',
 '3',
 'timer.educ.4_First Click',
 'timer.educ.4_Last Click',
 'timer.educ.4_Page Submit',
 'timer.educ.4_Click Count',
 'educ_4',
 '4',
 'timer.educ.5_First Click',
 'timer.educ.5_Last Click',
 'timer.educ.5_Page Submit',
 'timer.educ.5_Click Count',
 'educ_5',
 '5',
 'timer.educ.6_First Click',
 'timer.educ.6_Last Click',
 'timer.educ.6_Page Submit',
 'timer.educ.6_Click Count',
 'educ_6',
 '6',
 'timer.educ.7_First Click',
 'timer.educ.7_Last Click',
 'timer.educ.7_Page Submit',
 'timer.educ.7_Click Count',
 'educ_7',
 '7',
 'timer.educ.8_First Click',
 'timer.educ.8_Last Click',
 'timer.educ.8_Page Submit',
 'timer.educ.8_Click Count',
 'educ_8',
 '8',
 'timer.image.9_First Click',
 'timer.image.9_Last Click',
 'timer.image.9_Page Submit',
 'timer.image.9_Click Count',
 'educ_9',
 '9',
 'timer.instructions_First Click',
 'timer.instructions_Last Click',
 'timer.instructions_Page Submit',
 'timer.instructions_Click Count',
 'PROLIFIC_PID',
 'STUDY_ID',
 'SESSION_ID',
 'Invite_Block',
 'platforms_fb_n',
 'platforms_insta_n',
 'platforms_tiktok_n',
 'platforms_truth_n',
 'platforms_x_n',
 'smu',
 'condition',
 'pre_ih',
 'post_ih',
 'delta_ih',
 'race_new',
 'pid7',
 'new_educ',
 'new_educ_num',
 'total_duration',
 'zip_state',
 'third_order_A1',
 'third_order_A2',
 'third_order_B1',
 'third_order_B2',
 'future_use_n',
 'engaging',
 'toxic',
 'exhausting',
 'platform',
 'polite',
 'aggressive',
 'tolerant',
 'users',
 'users_b',
 'comfort',
 'total_likes',
 'ih_likes',
 'p_likes_ih',
 'total_dislikes',
 'ih_dislikes',
 'p_dislikes_ih',
 'n_posts',
 'total_length',
 'sent_pos',
 'sent_neg',
 'sent',
 'text',
 'all_dwell',
 'ih_dwell',
 'ih_dwell_log',
 'ih_dwell_p',
 'mc_correct',
 'n_op',
 'n_comments',
 'zip_state_match',
 'speeder',
 'commented',
 'posted',
 'passcode',
 'gold_star',
 'posit',
 'ih_a_ca',
 'ih_b_ca',
 'tox_a_ca',
 'tox_b_ca']

In [38]:
ys = list(new_df.columns)[1:25] + list(new_df.columns)[-4:]

for y in ys:
    print(y, ": ", stats.ttest_ind(new_df[new_df.condition == "treat"][y],
                                   new_df[new_df.condition == "control"][y],
                                   nan_policy="omit"))

ih_a_all :  Ttest_indResult(statistic=2.0428747340981777, pvalue=0.04133222593673377)
ih_b_all :  Ttest_indResult(statistic=2.0395140047792326, pvalue=0.04166682328167753)
tox_a_all :  Ttest_indResult(statistic=0.9931792781827891, pvalue=0.3208680019837121)
tox_b_all :  Ttest_indResult(statistic=0.9113809948129217, pvalue=0.36231901323527327)
ih_a_op :  Ttest_indResult(statistic=2.6476232430026703, pvalue=0.008251477465826445)
ih_b_op :  Ttest_indResult(statistic=2.1919595444939692, pvalue=0.028644655104448878)
tox_a_op :  Ttest_indResult(statistic=0.8326744644871502, pvalue=0.4052550415053088)
tox_b_op :  Ttest_indResult(statistic=0.8935443716607412, pvalue=0.37181085276290793)
ih_a_comm :  Ttest_indResult(statistic=1.0760915437358418, pvalue=0.28218531933341195)
ih_b_comm :  Ttest_indResult(statistic=1.1488456385982624, pvalue=0.25093611671529886)
tox_a_comm :  Ttest_indResult(statistic=1.19591240080014, pvalue=0.23205733533524686)
tox_b_comm :  Ttest_indResult(statistic=0.9503955701757499, pvalue=0.3421758402836643)
ih_a_ih :  Ttest_indResult(statistic=-1.3233487967128648, pvalue=0.18675819466513338)
ih_b_ih :  Ttest_indResult(statistic=-1.715231544814927, pvalue=0.08736727999125947)
tox_a_ih :  Ttest_indResult(statistic=-0.47801957339887935, pvalue=0.6329951652044519)
tox_b_ih :  Ttest_indResult(statistic=-0.648738063290796, pvalue=0.5170193209820247)
ih_a_con :  Ttest_indResult(statistic=0.06040635819717979, pvalue=0.9518559873108989)
ih_b_con :  Ttest_indResult(statistic=0.03050275317529302, pvalue=0.9756781965548271)
tox_a_con :  Ttest_indResult(statistic=0.7700218905760364, pvalue=0.4416483861369431)
tox_b_con :  Ttest_indResult(statistic=0.47182484537394276, pvalue=0.6372564184494744)
ih_a_lib :  Ttest_indResult(statistic=1.197863011434897, pvalue=0.23157665369443023)
ih_b_lib :  Ttest_indResult(statistic=1.9186847765327353, pvalue=0.055632216055062945)
tox_a_lib :  Ttest_indResult(statistic=0.4987275559759683, pvalue=0.6182056501935492)
tox_b_lib :  Ttest_indResult(statistic=0.5094047531340197, pvalue=0.6107086495523399)
ih_a_ca :  Ttest_indResult(statistic=-0.727448106881151, pvalue=0.4673666770396676)
ih_b_ca :  Ttest_indResult(statistic=-0.4313219579486968, pvalue=0.6664609825952815)
tox_a_ca :  Ttest_indResult(statistic=0.5722866738964121, pvalue=0.5674414326076713)
tox_b_ca :  Ttest_indResult(statistic=0.09981869259501353, pvalue=0.920537056019926)

In [39]:
for y in ys:
    r = stats.mannwhitneyu(new_df[new_df.condition == "treat"][y],
                           new_df[new_df.condition == "control"][y],
                           nan_policy="omit")
    if r[1] < 0.05:
        print(y, r)

ih_a_all MannwhitneyuResult(statistic=129001.0, pvalue=0.04326904542276676)
ih_b_all MannwhitneyuResult(statistic=129535.0, pvalue=0.032227463951556165)
ih_a_op MannwhitneyuResult(statistic=106192.0, pvalue=0.008349993871546618)
ih_b_op MannwhitneyuResult(statistic=104436.0, pvalue=0.029985235156663417)

In [40]:
for y in ys:
    r = stats.ttest_ind(new_df[new_df.condition == "treat"][y],
                        new_df[new_df.condition == "control"][y],
                        nan_policy="omit")
    if r[1] < 0.05:
        print(y, r)

ih_a_all Ttest_indResult(statistic=2.0428747340981777, pvalue=0.04133222593673377)
ih_b_all Ttest_indResult(statistic=2.0395140047792326, pvalue=0.04166682328167753)
ih_a_op Ttest_indResult(statistic=2.6476232430026703, pvalue=0.008251477465826445)
ih_b_op Ttest_indResult(statistic=2.1919595444939692, pvalue=0.028644655104448878)

In [41]:
data = []
for y in ys:
    x1 = new_df[new_df.condition == "treat"][y]
    x2 = new_df[new_df.condition == "control"][y]

    d = (x1.mean() - x2.mean()) / new_df[y].std()
    
    u = stats.mannwhitneyu(x1,x2,nan_policy="omit")
    t = stats.ttest_ind(x1,x2,nan_policy="omit")
    
    data.append({"U": u[0],
                 "U_p": u[1],
                 "t": t[0],
                 "t_p": t[1],
                 "y": y,
                 "mu_control": x2.mean(),
                 "mu_treat": x1.mean(),
                 "eta_control": x2.median(),
                 "eta_treat": x1.median(),
                 "d": d})

effects_df = pd.DataFrame(data)
effects_df

,U,U_p,t,t_p,y,mu_control,mu_treat,eta_control,eta_treat,d
0,129001.0,0.043269,2.042875,0.041332,ih_a_all,0.319104,0.332514,0.314348,0.325050,0.130374
1,129535.0,0.032227,2.039514,0.041667,ih_b_all,0.323467,0.337218,0.312011,0.329134,0.130161
2,126715.0,0.132230,0.993179,0.320868,tox_a_all,0.081807,0.086362,0.058698,0.065192,0.063487
3,126651.0,0.135981,0.911381,0.362319,tox_b_all,0.037428,0.039555,0.024072,0.028153,0.058263
4,106192.0,0.008350,2.647623,0.008251,ih_a_op,0.286114,0.308898,0.266263,0.294537,0.178273
5,104436.0,0.029985,2.191960,0.028645,ih_b_op,0.325588,0.346420,0.306997,0.331816,0.147776
6,98096.5,0.628909,0.832674,0.405255,tox_a_op,0.102431,0.108153,0.065797,0.064610,0.056268
7,98265.0,0.597429,0.893544,0.371811,tox_b_op,0.046395,0.049673,0.026709,0.026854,0.060378
8,98220.0,0.295508,1.076092,0.282185,ih_a_comm,0.347354,0.356303,0.347937,0.354113,0.073061
9,99342.0,0.177244,1.148846,0.250936,ih_b_comm,0.328301,0.337288,0.319651,0.329327,0.077994
10,98647.0,0.245440,1.195912,0.232057,tox_a_comm,0.065547,0.071585,0.035556,0.039148,0.081184
11,97671.0,0.369308,0.950396,0.342176,tox_b_comm,0.030302,0.032601,0.015282,0.016280,0.064537
12,9666.5,0.205738,-1.323349,0.186758,ih_a_ih,0.369610,0.348541,0.368125,0.350299,-0.155537
13,9494.5,0.132509,-1.715232,0.087367,ih_b_ih,0.349798,0.324659,0.332301,0.319884,-0.201187
14,9868.0,0.324379,-0.478020,0.632995,tox_a_ih,0.079095,0.073124,0.039227,0.027616,-0.056330
15,9753.5,0.252404,-0.648738,0.517019,tox_b_ih,0.037364,0.033343,0.016355,0.012200,-0.076422
16,31987.5,0.845236,0.060406,0.951856,ih_a_con,0.325698,0.326421,0.317497,0.317272,0.005399
17,32335.5,0.683166,0.030503,0.975678,ih_b_con,0.310943,0.311280,0.296360,0.298735,0.002726
18,34063.0,0.142858,0.770022,0.441648,tox_a_con,0.077594,0.084552,0.036203,0.041173,0.068786
19,33341.5,0.305962,0.471825,0.637256,tox_b_con,0.036452,0.038547,0.015331,0.016003,0.042163
20,29258.0,0.263706,1.197863,0.231577,ih_a_lib,0.354194,0.368597,0.371917,0.378950,0.110456
21,30322.0,0.065713,1.918685,0.055632,ih_b_lib,0.325730,0.346861,0.332027,0.350633,0.176502
22,29851.0,0.128394,0.498728,0.618206,tox_a_lib,0.061324,0.065217,0.024260,0.026676,0.046046
23,29572.0,0.183204,0.509405,0.610709,tox_b_lib,0.028149,0.030065,0.011796,0.012465,0.047032
24,20273.0,0.458670,-0.727448,0.467367,ih_a_ca,0.330259,0.320375,0.318006,0.304590,-0.071803
25,20948.0,0.855706,-0.431322,0.666461,ih_b_ca,0.316558,0.310999,0.294652,0.293363,-0.042592
26,22858.0,0.161617,0.572287,0.567441,tox_a_ca,0.078470,0.083943,0.035102,0.040865,0.056502
27,22347.0,0.328908,0.099819,0.920537,tox_b_ca,0.036909,0.037375,0.015226,0.016422,0.009859

In [42]:
effects_df[['y','d','t_p']]

             y         d       t_p
0     ih_a_all  0.130374  0.041332
1     ih_b_all  0.130161  0.041667
2    tox_a_all  0.063487  0.320868
3    tox_b_all  0.058263  0.362319
4      ih_a_op  0.178273  0.008251
5      ih_b_op  0.147776  0.028645
6     tox_a_op  0.056268  0.405255
7     tox_b_op  0.060378  0.371811
8    ih_a_comm  0.073061  0.282185
9    ih_b_comm  0.077994  0.250936
10  tox_a_comm  0.081184  0.232057
11  tox_b_comm  0.064537  0.342176
12     ih_a_ih -0.155537  0.186758
13     ih_b_ih -0.201187  0.087367
14    tox_a_ih -0.056330  0.632995
15    tox_b_ih -0.076422  0.517019
16    ih_a_con  0.005399  0.951856
17    ih_b_con  0.002726  0.975678
18   tox_a_con  0.068786  0.441648
19   tox_b_con  0.042163  0.637256
20    ih_a_lib  0.110456  0.231577
21    ih_b_lib  0.176502  0.055632
22   tox_a_lib  0.046046  0.618206
23   tox_b_lib  0.047032  0.610709
24     ih_a_ca -0.071803  0.467367
25     ih_b_ca -0.042592  0.666461
26    tox_a_ca  0.056502  0.567441
27    tox_b_ca  0.009859  0.920537

In [43]:
effects_df[(effects_df.t_p < 0.05)|(effects_df.U_p < 0.05)].sort_values('y')

,U,U_p,t,t_p,y,mu_control,mu_treat,eta_control,eta_treat,d
0,129001.0,0.043269,2.042875,0.041332,ih_a_all,0.319104,0.332514,0.314348,0.325050,0.130374
4,106192.0,0.008350,2.647623,0.008251,ih_a_op,0.286114,0.308898,0.266263,0.294537,0.178273
1,129535.0,0.032227,2.039514,0.041667,ih_b_all,0.323467,0.337218,0.312011,0.329134,0.130161
5,104436.0,0.029985,2.191960,0.028645,ih_b_op,0.325588,0.346420,0.306997,0.331816,0.147776

In [44]:
effects_df[(effects_df.t_p < 0.05)&(effects_df.U_p < 0.05)]

,U,U_p,t,t_p,y,mu_control,mu_treat,eta_control,eta_treat,d
0,129001.0,0.043269,2.042875,0.041332,ih_a_all,0.319104,0.332514,0.314348,0.325050,0.130374
1,129535.0,0.032227,2.039514,0.041667,ih_b_all,0.323467,0.337218,0.312011,0.329134,0.130161
4,106192.0,0.008350,2.647623,0.008251,ih_a_op,0.286114,0.308898,0.266263,0.294537,0.178273
5,104436.0,0.029985,2.191960,0.028645,ih_b_op,0.325588,0.346420,0.306997,0.331816,0.147776

# Analysis by Time

## Time Bucket Analysis

In [47]:
post_info

,sessionId,treatmentArm,participantCode,profilePicture,firstName,lastName,bio,postOrCommentId,userContent,staticContent,...,INSULT_EXPERIMENTAL,PROFANITY_EXPERIMENTAL,THREAT_EXPERIMENTAL,SEXUALLY_EXPLICIT,FLIRTATION,perspective_toxicity_agg,ih_austin_a,ih_austin_b,tox_austin_a,tox_austin_b
0,657895d16d158d001f181302,imm_pc,zf1er9,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Ginger,NaN,I love cats!,657897906d158d001f182280,1,0,...,0.127028,0.077732,0.010784,0.038217,0.340470,0.128365,0.469136,0.438154,0.254629,0.120118
1,657895d16d158d001f181302,imm_pc,zf1er9,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Ginger,NaN,I love cats!,657899146d158d001f1856cc,1,0,...,0.033460,0.017778,0.006965,0.006812,0.556122,0.110948,0.351996,0.417278,0.150481,0.061872
2,657895d16d158d001f181302,imm_pc,zf1er9,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Ginger,NaN,I love cats!,657899606d158d001f1862d5,1,0,...,0.007513,0.011714,0.006848,0.006193,0.241154,0.035897,0.459829,0.369664,0.010807,0.006681
3,657896b96d158d001f181516,imm_treat,8gch37,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Yelena22,NaN,NC girl,657898246d158d001f18395d,1,0,...,0.248355,0.045670,0.006965,0.009672,0.299508,0.150781,0.342446,0.345526,0.309935,0.170582
4,657896b96d158d001f181516,imm_treat,8gch37,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Yelena22,NaN,NC girl,657899456d158d001f185f72,1,0,...,0.007969,0.010502,0.006045,0.003052,0.224278,0.033593,0.382053,0.364194,0.012817,0.006676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4389,657b61122855e7001f93f0ef,imm_control3,pqdpcp,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Cbros,NaN,Baba,657b62628b12dc001f05d62b,1,0,...,0.027089,0.019554,0.008117,0.004954,0.225375,0.067105,0.128559,0.156050,0.142560,0.057711
4390,657b64a78b12dc001f06215b,imm_control3,h63zav,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Shan,NaN,"Jersey girl, born and raised!!! I love animals...",657b65a88b12dc001f069f70,1,0,...,0.035223,0.032894,0.033732,0.014331,0.453156,0.096431,0.093467,0.090807,0.172851,0.056027
4391,657b64a78b12dc001f06215b,imm_control3,h63zav,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Shan,NaN,"Jersey girl, born and raised!!! I love animals...",657b66162855e7001f9554e3,1,0,...,0.012605,0.015147,0.007806,0.008434,0.351283,0.055717,0.548232,0.509349,0.032156,0.015593
4392,657b64a78b12dc001f06215b,imm_control3,h63zav,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Shan,NaN,"Jersey girl, born and raised!!! I love animals...",657b66cb8b12dc001f07eca7,1,0,...,0.012377,0.010314,0.006654,0.003155,0.388082,0.056238,0.284360,0.376801,0.024496,0.010128
4393,657b64a78b12dc001f06215b,imm_control3,h63zav,https://sma2-prod.s3.amazonaws.com/animal%2C%2...,Shan,NaN,"Jersey girl, born and raised!!! I love animals...",657b670e8b12dc001f085097,1,0,...,0.063899,0.025907,0.028379,0.007461,0.290690,0.116695,0.111967,0.118499,0.270478,0.121585

## Time-based Ablation Analysis